name: gql_http_link
version: 0.4.2
description: GQL Terminating Link to execute requests via HTTP using JSON.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  gql: ^0.13.0
  gql_exec: ^0.4.0
  gql_link: ^0.4.2
  http: ^0.13.0
  http_parser: ^4.0.0
  meta: ^1.3.0
dev_dependencies: 
  build_runner: ^2.0.0
  gql_pedantic: ^1.0.2
  mockito: ^5.0.0-nullsafety.7
  test: ^1.16.2
