name: gql_error_link
version: 0.2.0
description: GQL Link to handle execution errors and exceptions
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.5.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  meta: ^1.3.0
dev_dependencies: 
  test: ^1.16.2
  mockito: ^5.0.0-nullsafety.7
  gql: ^0.13.0
  gql_pedantic: ^1.0.2
