name: gql_example_cli_github
environment: 
  sdk: '>=2.2.0 <3.0.0'
dependencies: 
  args: any
  gql: ^0.12.1
  gql_link: ^0.2.3
  gql_exec: ^0.2.2
  gql_http_link: ^0.2.3
  gql_transform_link: ^0.1.4
dev_dependencies: 
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.1
  gql_build: ^0.0.5
