name: gql_example_flutter
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  gql: ^1.0.0
  gql_link: ^1.0.0
  gql_http_link: ^1.0.0
  gql_exec: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.0.0
  gql_pedantic: ^1.0.2
  gql_build: ^0.7.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
