name: gql_websocket_link
version: 1.0.0
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.15.0 <4.0.0'
dependencies: 
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  meta: ^1.3.0
  rxdart: '>=0.26.0 <0.28.0'
  uuid: ^3.0.1
  web_socket_channel: ^2.0.0
dev_dependencies: 
  gql_pedantic: ^1.0.2
  mockito: ^5.0.0
  test: ^1.16.6
