name: gql_websocket_link
version: 0.3.3
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  gql: ^0.13.0
  gql_exec: ^0.4.0
  gql_link: ^0.4.2
  meta: ^1.3.0
  rxdart: ^0.26.0
  uuid: ^3.0.1
  web_socket_channel: ^2.0.0
dev_dependencies: 
  gql_pedantic: ^1.0.2
  mockito: ^5.0.0
  test: ^1.16.6
