name: gql_websocket_link
version: 0.1.5
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  meta: ^1.1.8
  gql_exec: ^0.2.5
  gql_link: ^0.3.1
  uuid_enhanced: ^3.0.2
  rxdart: ^0.25.0
  gql: ^0.12.3
  web_socket_channel: ^1.1.0
dev_dependencies: 
  test: ^1.14.3
  mockito: ^4.1.1
  gql_pedantic: ^1.0.2
