name: gql_example_http_auth_link
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  gql: ^1.0.0
  gql_error_link: ^1.0.0
  gql_exec: ^1.0.0
  gql_http_link: ^1.0.0
  gql_link: ^1.0.0
  gql_transform_link: ^1.0.0
  http: ^0.13.1
dev_dependencies: 
  gql_build: ^0.7.0
  gql_pedantic: ^1.0.2
