name: gql_transform_link
version: 1.0.0
description: GQL Link to transform Requests and Responses. May be used to update context, document, variables, data, errors, etc.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
dev_dependencies: 
  gql: ^1.0.0
  gql_pedantic: ^1.0.2
  mockito: ^5.0.0-nullsafety.7
  test: ^1.16.2
