name: gql_pedantic
version: 1.1.0
description: Even more opinionated lint rules.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependency_overrides: 
  gql: 
    path: ../gql
  gql_exec: 
    path: ../links/gql_exec
  gql_link: 
    path: ../links/gql_link
  gql_websocket_link: 
    path: ../links/gql_websocket_link
  gql_tristate_value: 
    path: ../codegen/gql_tristate_value
  gql_transform_link: 
    path: ../links/gql_transform_link
  gql_http_link: 
    path: ../links/gql_http_link
  gql_error_link: 
    path: ../links/gql_error_link
  gql_code_builder: 
    path: ../codegen/gql_code_builder
  gql_build: 
    path: ../codegen/gql_build
  gql_example_http_auth_link: 
    path: ../examples/gql_example_http_auth_link
  gql_dio_link: 
    path: ../links/gql_dio_link
  gql_example_dio_link: 
    path: ../examples/gql_example_dio_link
  gql_example_cli_github: 
    path: ../examples/gql_example_cli_github
  gql_example_cli: 
    path: ../examples/gql_example_cli
  gql_example_build: 
    path: ../examples/gql_example_build
  gql_dedupe_link: 
    path: ../links/gql_dedupe_link
  end_to_end_test_tristate: 
    path: ../codegen/end_to_end_test_tristate
  end_to_end_test: 
    path: ../codegen/end_to_end_test
