name: gql_link
version: 1.0.0
description: A simple and modular AST-based GraphQL request execution interface.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  gql: ^1.0.0
  gql_exec: ^1.0.0
  meta: ^1.1.7
dev_dependencies: 
  gql_pedantic: ^1.0.2
  mockito: ^5.0.16
  test: ^1.16.2
