name: gql
version: 1.0.0
description: GraphQL tools for parsing, transforming and printing GraphQL documents.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  collection: ^1.15.0
  meta: ^1.3.0
  source_span: ^1.8.0
  yaml: ^3.0.0
dev_dependencies: 
  gql_pedantic: ^1.0.2
  test: ^1.16.2
