name: gql
version: 0.12.3
homepage: https://github.com/gql-dart/gql/tree/master/gql
description: GraphQL tools for parsing, transforming and printing GraphQL documents.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  source_span: ^1.5.5
  meta: ^1.1.7
  collection: ^1.14.11
dev_dependencies: 
  test: ^1.0.0
  gql_pedantic: ^1.0.1
  cats: 
    path: ../cats
