name: end_to_end_test_repro
version: 0.0.1
publish_to: none
description: Tests, not for publishing. Uses the original version of codegen without tristate optionals.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  built_collection: ^5.0.0
  built_value: ^8.0.6
  gql_exec: ^1.0.0
  gql_build: ^0.8.0
  gql_code_builder: ^0.7.1
dev_dependencies: 
  build: ^2.0.0
  build_runner: ^2.0.0
  test: ^1.16.8
