name: gql_code_builder
author: Klāvs Priedītis <klavs@prieditis.lv>
version: 0.0.1
homepage: https://github.com/gql-dart/gql/tree/master/gql_code_builder
description: GraphQL code generator and file builder for Dart taking *.graphql files as an input.
environment: 
  sdk: '>=2.2.2 <3.0.0'
dependencies: 
  gql: ^0.12.0
  code_builder: ^3.2.0
  meta: ^1.1.7
  built_collection: ^4.0.0
dev_dependencies: 
  test: ^1.0.0
  gql_pedantic: ^1.0.0
