name: gql_exec
version: 1.0.0
description: Basis for GraphQL execution layer to support Link and Client.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  collection: ^1.15.0
  gql: ^1.0.0
  meta: ^1.3.0
dev_dependencies: 
  gql_pedantic: ^1.0.2
  test: ^1.16.2
