name: gql_exec
version: 0.3.0
description: Basis for GraphQL execution layer to support Link and Client.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  collection: ^1.15.0
  meta: ^1.3.0
  gql: ^0.13.0
dev_dependencies: 
  test: ^1.16.2
  gql_pedantic: ^1.0.2
