name: gql_example_dio_link
description: A simple example to show gql_dio_link
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  dio: ^4.0.0
  gql: ^0.13.0
  gql_link: ^0.4.2
  gql_exec: ^0.4.0
  gql_dio_link: ^0.1.0
