name: gql_dio_link
version: 0.2.3
description: Similar to gql_http_link, gql_dio_link is a GQL Terminating Link to execute requests via Dio using JSON
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  dio: ^4.0.0
  gql: ^0.14.0
  gql_exec: ^0.4.0
  gql_link: ^0.5.0
  meta: ^1.3.0
dev_dependencies: 
  build_runner: ^2.0.0
  code_builder: ^4.2.0
  collection: ^1.15.0
  gql_pedantic: ^1.0.2
  mockito: ^5.3.0
  test: ^1.14.3
