name: gql_dio_link
version: 1.0.1
description: Similar to gql_http_link, gql_dio_link is a GQL Terminating Link to execute requests via Dio using JSON
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.13.0 <4.0.0'
dependencies: 
  dio: ^5.2.0+1
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  meta: ^1.3.0
dev_dependencies: 
  build_runner: ^2.0.0
  code_builder: ^4.2.0
  collection: ^1.15.0
  gql_pedantic: ^1.0.2
  http_parser: ^4.0.0
  mockito: ^5.3.0
  test: ^1.14.3
