name: gql_build
version: 0.0.11
homepage: https://github.com/gql-dart/gql/tree/master/gql_build
description: Useful builders for your GraphQL SDL and documents. Based on package:gql_code_builder and package:build
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  gql: ^0.12.1
  path: ^1.6.4
  glob: ^1.2.0
  build: ^1.0.0
  gql_code_builder: ^0.0.9
  code_builder: ^3.2.0
  dart_style: ^1.2.9
dev_dependencies: 
  test: ^1.0.0
  build_test: ^0.10.7
  gql_pedantic: ^1.0.1
