name: gql_dedupe_link
version: 2.0.3+1
description: GQL Link to deduplicate identical in-flight execution requests
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  async: ^2.5.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  meta: ^1.3.0
dev_dependencies: 
  gql: ^1.0.0
  gql_pedantic: ^1.0.2
  mockito: ^5.0.0-nullsafety.7
  test: ^1.16.2
