name: gql_dedupe_link
version: 2.0.0
description: GQL Link to deduplicate identical in-flight execution requests
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.3.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  async: ^2.5.0
dev_dependencies: 
  test: ^1.16.2
  mockito: ^5.0.0-nullsafety.7
  gql: ^0.13.0
  gql_pedantic: ^1.0.2
