name: gql_example_cli_github
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  args: ^2.0.0
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_http_link: ^1.0.0
  gql_link: ^1.0.0
  gql_transform_link: ^1.0.0
dev_dependencies: 
  build_runner: ^2.0.0
  dart_style: ^2.3.1
  gql_build: ^0.7.0
  gql_pedantic: ^1.0.2
