name: gql_example_cli_github
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  args: ^2.0.0
  gql: ^0.14.0
  gql_exec: ^0.4.3
  gql_http_link: ^0.4.4+1
  gql_link: ^0.5.0
  gql_transform_link: ^0.2.2
dev_dependencies: 
  analyzer: ^5.10.0
  build_runner: ^2.4.1
  gql_build: ^0.7.0
  gql_pedantic: ^1.0.2
  matcher: ^0.12.15
