name: gql_code_builder
version: 0.0.10
homepage: https://github.com/gql-dart/gql/tree/master/gql_code_builder
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  gql: ^0.12.1
  code_builder: ^3.2.0
  meta: ^1.1.7
  built_collection: ^4.0.0
dev_dependencies: 
  gql_pedantic: ^1.0.1
