name: gql_code_builder
version: 0.0.10
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  gql: ^0.12.1
  code_builder: ^3.3.0
  meta: ^1.1.7
  built_collection: ^4.0.0
  built_value: ^7.0.9
  path: ^1.6.4
  recase: ^3.0.0
  gql_exec: ^0.2.4
dev_dependencies:
  gql_pedantic: ^1.0.1
  build_runner: ^1.7.4
