name: gql_code_builder
version: 0.7.2
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  analyzer: '>=4.6.0 <6.0.0'
  built_collection: ^5.0.0
  built_value: ^8.0.6
  code_builder: ^4.3.0
  collection: ^1.15.0
  gql: ^1.0.0
  gql_exec: ^1.0.0
  path: ^1.8.0
dev_dependencies: 
  build_runner: ^2.1.0
  gql_pedantic: ^1.0.2
  test: ^1.16.8
