name: gql_code_builder
version: 0.2.0
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^1.2.0
  built_collection: ^5.0.0
  built_value: ^8.0.4
  code_builder: ^3.7.0
  gql: ^0.13.0-nullsafety.2
  gql_exec: ^0.3.0-nullsafety.2
  path: ^1.8.0
  recase: ^4.0.0-nullsafety.0
dev_dependencies:
  build_runner: ^1.12.2
  gql_pedantic: ^1.0.2
  test: ^1.16.8
