name: gql_code_builder
version: 0.6.0
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  analyzer: '>=4.2.0 <5.0.0'
  built_collection: ^5.0.0
  built_value: ^8.0.6
  code_builder: ^4.0.0
  collection: ^1.15.0
  gql: ^0.14.0
  gql_exec: ^0.4.0
  path: ^1.8.0
dev_dependencies: 
  build_runner: ^2.1.0
  gql_pedantic: ^1.0.2
  test: ^1.16.8
dependency_overrides: 
  gql_pedantic: 
    path: ../../gql_pedantic
  gql: 
    path: ../../gql
  gql_exec: 
    path: ../../links/gql_exec
  gql_link: 
    path: ../../links/gql_link
  gql_websocket_link: 
    path: ../../links/gql_websocket_link
  gql_transform_link: 
    path: ../../links/gql_transform_link
  gql_http_link: 
    path: ../../links/gql_http_link
  gql_error_link: 
    path: ../../links/gql_error_link
  gql_build: 
    path: ../gql_build
  gql_example_http_auth_link: 
    path: ../../examples/gql_example_http_auth_link
  gql_dio_link: 
    path: ../../links/gql_dio_link
  gql_example_dio_link: 
    path: ../../examples/gql_example_dio_link
  gql_example_cli_github: 
    path: ../../examples/gql_example_cli_github
  gql_example_cli: 
    path: ../../examples/gql_example_cli
  gql_example_build: 
    path: ../../examples/gql_example_build
  gql_dedupe_link: 
    path: ../../links/gql_dedupe_link
  end_to_end_test: 
    path: ../end_to_end_test
