name: gql_link
version: 0.3.0
homepage: https://github.com/gql-dart/gql/tree/master/gql_link
description: A simple and modular AST-based GraphQL request execution interface.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  meta: ^1.1.7
  gql: ^0.12.1
  gql_exec: ^0.2.2
dev_dependencies: 
  test: ^1.0.0
  mockito: ^4.1.1
  gql_pedantic: ^1.0.1
